[package]
name = "orion-lang"
version = "0.1.0"
authors = ["Wafelack <wafelack@protonmail.com>"]
edition = "2018"

[[bin]]
name = "orion"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[dependencies]
rustyline = "7.1.0"
clap = "2.33.3"
